[build]
  publish = "dist/JYZV-0387-PORTFOLIO-DEV-NG-00"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/en/index.html"
  status = 200
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/en/*"
  to = "/en/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/es/index.html"
  status = 200